import { connectToDB } from "../config/database";

const createTables = async () => {
    const scripts = [
        // Adicione os scripts de criação de tabelas aqui
        `
        CREATE TABLE Users (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            name VARCHAR2(100) NOT NULL,
            email VARCHAR2(100) UNIQUE NOT NULL,
            password VARCHAR2(200) NOT NULL,
            wallet_balance NUMBER(10, 2) DEFAULT 0 NOT NULL,
            is_moderator CHAR(1) DEFAULT 'N' CHECK (is_moderator IN ('Y', 'N'))
        )
        `,
        `
        CREATE TABLE Events (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            title VARCHAR2(50) NOT NULL,
            description VARCHAR2(150),
            bet_amount NUMBER(10, 2) NOT NULL,
            start_date DATE NOT NULL,
            end_date DATE NOT NULL,
            result CHAR(1) DEFAULT NULL CHECK (result IN ('Y', 'N')),
            status VARCHAR2(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'finished', 'deleted')),
            creator_id NUMBER NOT NULL,
            FOREIGN KEY (creator_id) REFERENCES Users(id) ON DELETE CASCADE
        )
        `,
        `
        CREATE TABLE Bets (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            event_id NUMBER NOT NULL,
            user_id NUMBER NOT NULL,
            amount NUMBER(10, 2) NOT NULL,
            prediction CHAR(1) NOT NULL CHECK (prediction IN ('Y', 'N')),
            FOREIGN KEY (event_id) REFERENCES Events(id) ON DELETE CASCADE,
            FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
        )
        `,
        `
        CREATE TABLE WalletTransactions (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            user_id NUMBER NOT NULL,
            amount NUMBER(10, 2) NOT NULL,
            type VARCHAR2(20) NOT NULL CHECK (type IN ('deposit', 'withdraw')),
            details VARCHAR2(255),
            timestamp DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
        )
        `
    ];

    try {
        const connection = await connectToDB();

        for (const script of scripts) {
            console.log(`Executando script:\n${script}`);
            await connection.execute(script);
        }

        await connection.commit();
        console.log("Tabelas criadas com sucesso!");
        await connection.close();
    } catch (error) {
        console.error("Erro ao criar tabelas:", error);
    }
};

export default createTables;
